### ISSUE TITLE
Add package to packagist with right composer.json

### ISSUE THREAD

**Issue by seyfer** [gimpe/kohana-memcached#2]
See example in my repos. Add type as kohana-module.

Please, do it, or i will fork and do it by myself.

**Comment by gimpe** [comment]
Good idea, I will do it.

**Comment by seyfer** [comment]
https://github.com/gimpe/kohana-memcached/commit/3c7345c833ca99fe8f572337e03f3fbb7f49d901

You do it wrong
Name should be vendor/modulename

and you write "type" twice

if you not fix it - you can't add to packagist

**Comment by gimpe** [comment]
Thanks, I think I got it right now.

**Comment by gimpe** [comment]
https://packagist.org/packages/gimpe/kohana-memcached

**Comment by seyfer** [comment]
@gimpe, Thak you

**Comment by seyfer** [comment]
Sorry, but it's not all complete.

Please, add composer.json to 3.3 and 3.2 branch too, and than update your packagist repo.
Many developers still have ko3.2

**Comment by gimpe** [comment]
@seyfer This is my first time addind a projec to packagist. Thanks for your help!

**Comment by seyfer** [comment]
@gimpe , thank you for doing that!
